language: go

go:
  - 1.11.x

git:
  depth: 1

cache:
  directories:
    - /home/travis/cache

services:
  - redis

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
      sudo sh -c 'echo "\n::1 localhost\n" >> /etc/hosts';
    fi

before_install:
  - source scripts/setup-gopath.sh

matrix:
  include:
    - env: MODE=tests
      install:
        - pushd ~
        - GOBIN=${GOPATH}/bin GOPATH=~/gotools go get github.com/mattn/goveralls
        - popd
        - go install -race ./...
      script:
        - go test -race -cover -coverprofile=.coverprofile ./...
        - goveralls -coverprofile=.coverprofile -service=travis-ci
    - env: MODE=lint
      install:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b ${GOPATH}/bin v1.10.2
      script:
        - ./scripts/check-for-header.sh
        - golangci-lint run
    - env: MODE=integration
      install:
        - source scripts/install-awscli.sh
        - go install storj.io/storj/cmd/captplanet
      script:
        - make test-captplanet
  fast_finish: true
